# lab_6/docker-compose.yml
version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"           # зовнішній порт : внутрішній
    volumes:
      - ./:/app               # мапимо весь каталог у /app
    environment:
      FLASK_ENV: development # включає debug і автоперезапуск
      FLASK_APP: library_api.app
    command: flask run --host=0.0.0.0 --port=5000
    restart: unless-stopped
